export const COUNTRIES = [
  {
    flagCode: 'us',
    name: 'Estados Unidos',
    programs: 'Intercambio estudiantil, Investigación',
    institutions: 2,
    cities: 'Miami, Cambridge',
    photo: '/images/gatestowermit.jpg',
    universities: [
      {
        abbr: 'FIU',
        name: 'Florida International University',
        city: 'Miami, Florida',
        modality: 'Presencial',
        requirements: 'Promedio mín. 14/20, inglés B2, carta de motivación, seguro médico',
        deadline: '31 de marzo',
        vacancies: 5,
      },
      {
        abbr: 'HAR',
        name: 'Harvard University',
        city: 'Cambridge, Massachusetts',
        modality: 'Presencial / Virtual',
        requirements: 'Promedio mín. 16/20, inglés C1, entrevista con coordinador',
        deadline: '15 de enero',
        vacancies: 2,
      },
    ],
  },
  {
    flagCode: 'mx',
    name: 'México',
    programs: 'Intercambio estudiantil, Pasantías',
    institutions: 3,
    cities: 'Ciudad de México, Monterrey',
    photo: '/images/mexicocapital.jpg',
    universities: [
      {
        abbr: 'IBE',
        name: 'Universidad Iberoamericana',
        city: 'Ciudad de México',
        modality: 'Presencial',
        requirements: 'Promedio mín. 13/20, español avanzado, seguro médico',
        deadline: '31 de mayo',
        vacancies: 6,
      },
      {
        abbr: 'TEC',
        name: 'Tecnológico de Monterrey',
        city: 'Monterrey, Nuevo León',
        modality: 'Presencial / Virtual',
        requirements: 'Promedio mín. 14/20, carta de motivación, comprobante económico',
        deadline: '30 de abril',
        vacancies: 8,
      },
      {
        abbr: 'UNA',
        name: 'UNAM Univ. Nacional Autónoma',
        city: 'Ciudad de México',
        modality: 'Presencial',
        requirements: 'Promedio mín. 13/20, certificado de estudios, seguro médico',
        deadline: '15 de junio',
        vacancies: 5,
      },
    ],
  },
  {
    flagCode: 'co',
    name: 'Colombia',
    programs: 'Intercambio estudiantil, Investigación',
    institutions: 2,
    cities: 'Bogotá, Medellín',
    photo: '/images/UniandesBogota.jpg',
    universities: [
      {
        abbr: 'AND',
        name: 'Universidad de los Andes',
        city: 'Bogotá',
        modality: 'Presencial',
        requirements: 'Promedio mín. 14/20, carta de motivación, carta de recomendación',
        deadline: '30 de abril',
        vacancies: 4,
      },
      {
        abbr: 'ANT',
        name: 'Universidad de Antioquia',
        city: 'Medellín',
        modality: 'Presencial',
        requirements: 'Promedio mín. 13/20, carta de postulación, seguro médico',
        deadline: '15 de mayo',
        vacancies: 5,
      },
    ],
  },
  {
    flagCode: 'pe',
    name: 'Perú',
    programs: 'Intercambio estudiantil, Investigación',
    institutions: 3,
    cities: 'Lima, Huancayo',
    photo: '/images/Lima_Peru.jpg',
    universities: [
      {
        abbr: 'ULI',
        name: 'Universidad de Lima',
        city: 'Lima',
        modality: 'Presencial',
        requirements: 'Promedio mín. 13/20, carta de postulación, DNI vigente',
        deadline: '31 de julio',
        vacancies: 6,
      },
      {
        abbr: 'UCO',
        name: 'Universidad Continental',
        city: 'Lima / Huancayo',
        modality: 'Presencial / Virtual',
        requirements: 'Expediente académico, carta de postulación, convenio vigente',
        deadline: 'Continuo',
        vacancies: 10,
      },
      {
        abbr: 'MSM',
        name: 'Univ. Mayor de San Marcos',
        city: 'Lima',
        modality: 'Presencial',
        requirements: 'Promedio mín. 13/20, carta de postulación, seguro médico',
        deadline: '31 de mayo',
        vacancies: 5,
      },
    ],
  },
  {
    flagCode: 'ar',
    name: 'Argentina',
    programs: 'Intercambio estudiantil, Investigación',
    institutions: 2,
    cities: 'Buenos Aires',
    photo: '/images/Argentina.jpg',
    universities: [
      {
        abbr: 'UBA',
        name: 'Universidad de Buenos Aires',
        city: 'Buenos Aires',
        modality: 'Presencial',
        requirements: 'Promedio mín. 14/20, carta de motivación, seguro médico internacional',
        deadline: '30 de abril',
        vacancies: 5,
      },
       {
        abbr: 'UBC',
        name: 'UNIVERSIDAD ARGENTINA JOHN F. KENNEDY',
        city: 'Buenos Aires',
        modality: 'Presencial',
        requirements: 'Promedio mín. 14/20, carta de motivación, seguro médico internacional',
        deadline: '30 de abril',
        vacancies: 5,
      },
    ],
  },
  {
    flagCode: 'uy',
    name: 'Uruguay',
    programs: 'Intercambio estudiantil',
    institutions: 1,
    cities: 'Montevideo',
    photo: '/images/Uruguay.jpg',
    universities: [
      {
        abbr: 'UDE',
        name: 'Universidad de la República',
        city: 'Montevideo',
        modality: 'Presencial',
        requirements: 'Promedio mín. 13/20, carta de postulación, seguro médico',
        deadline: '31 de mayo',
        vacancies: 4,
      },
    ],
  },
  {
    flagCode: 'es',
    name: 'España',
    programs: 'Intercambio estudiantil, Investigación',
    institutions: 3,
    cities: 'Madrid, Salamanca',
    photo: '/images/España.jpg',
    universities: [
      {
        abbr: 'SAL',
        name: 'Universidad de Salamanca',
        city: 'Salamanca',
        modality: 'Presencial',
        requirements: 'Promedio mín. 14/20, español C1, visa de estudiante',
        deadline: '31 de marzo',
        vacancies: 5,
      },
      {
        abbr: 'CEU',
        name: 'CEU San Pablo',
        city: 'Madrid',
        modality: 'Presencial',
        requirements: 'Promedio mín. 14/20, español B2, seguro médico, visa',
        deadline: '15 de abril',
        vacancies: 4,
      },
      {
        abbr: 'FUE',
        name: 'Fundación Universidad-Empresa',
        city: 'Madrid',
        modality: 'Presencial / Virtual',
        requirements: 'Expediente académico, carta de postulación',
        deadline: '31 de mayo',
        vacancies: 6,
      },
    ],
  },
  {
    flagCode: 'de',
    name: 'Alemania',
    programs: 'Intercambio estudiantil, Investigación',
    institutions: 1,
    cities: 'Karlsruhe',
    photo: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=900&q=80',
    universities: [
      {
        abbr: 'KIT',
        name: 'Universitas Karlsruhe (KIT)',
        city: 'Karlsruhe',
        modality: 'Presencial',
        requirements: 'Promedio mín. 15/20, inglés B2 o alemán B2, carta de recomendación, visa',
        deadline: '31 de enero',
        vacancies: 3,
      },
    ],
  },
  {
    flagCode: 'br',
    name: 'Brasil',
    programs: 'Pasantías, Investigación',
    institutions: 1,
    cities: 'São Paulo',
    photo: '/images/Faculdade_de_Direito_do_Largo_de_Sao_Francisco.jpg',
    universities: [
      {
        abbr: 'USP',
        name: 'Univ. de São Paulo',
        city: 'São Paulo',
        modality: 'Presencial',
        requirements: 'Promedio mín. 14/20, portugués básico, carta de motivación, visa',
        deadline: '31 de mayo',
        vacancies: 5,
      },
    ],
  },
  {
    flagCode: 'za',
    name: 'Sudáfrica',
    programs: 'Intercambio estudiantil, Investigación',
    institutions: 1,
    cities: 'Ciudad del Cabo',
    photo: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=900&q=80',
    universities: [
      {
        abbr: 'UCT',
        name: 'University of Cape Town',
        city: 'Ciudad del Cabo',
        modality: 'Presencial',
        requirements: 'Promedio mín. 15/20, inglés B2, carta de motivación, visa de estudiante',
        deadline: '31 de julio',
        vacancies: 3,
      },
    ],
  },
  {
    flagCode: 'cl',
    name: 'Chile',
    programs: 'Intercambio estudiantil',
    institutions: 1,
    cities: 'Santiago',
    photo: '/images/Chile.jpg',
    universities: [
      {
        abbr: 'UCH',
        name: 'Universidad de Chile',
        city: 'Santiago',
        modality: 'Presencial',
        requirements: 'Promedio mín. 14/20, carta de motivación, seguro médico internacional',
        deadline: '30 de abril',
        vacancies: 4,
      },
    ],
  },
  {
    flagCode: 'cn',
    name: 'China',
    programs: 'Intercambio estudiantil, Investigación',
    institutions: 1,
    cities: 'Pekín',
    photo: 'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=900&q=80',
    universities: [
      {
        abbr: 'PKU',
        name: 'Peking University',
        city: 'Pekín',
        modality: 'Presencial',
        requirements: 'Promedio mín. 15/20, inglés B2 o chino A2, carta de motivación, visa',
        deadline: '28 de febrero',
        vacancies: 3,
      },
    ],
  },
];

// Map flagCode → COUNTRIES index for fast lookup
export const COUNTRY_MAP = Object.fromEntries(
  COUNTRIES.map((c, i) => [c.flagCode, i])
);

// ISO_A2 codes that match our countries (GeoJSON property)
export const OUR_ISO = new Set(['US','MX','CO','PE','AR','UY','CL','ES','DE','BR','ZA','CN']);
