export const COUNTRIES = [
  {
    flagCode: 'ar',
    name: 'Argentina',
    programs: 'Intercambio estudiantil',
    institutions: 11,
    cities: '',
    photo:'/images/Argentina.jpg',
    universities: [
      {
        abbr: 'UAJF',
        name: 'UNIVERSIDAD ARGENTINA JOHN F. KENNEDY',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'DERECHO, PSICOLOGÍA, ARQUITECTURA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, CONTABILIDAD, ODONTOLOGÍA',
        website: 'https://www.kennedy.edu.ar/',
      },
      {
        abbr: 'UDBA',
        name: 'UNIVERSIDAD DE BUENOS AIRES',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'DERECHO, CIENCIAS DE LA COMUNICACION, PSICOLOGÍA, ARQUITECTURA, INGENIERÍA CIVIL, INGENIERÍA ELÉCTRICA, INGENIERÍA INDUSTRIAL, INGENIERÍA MECÁNICA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, CONTABILIDAD, ECONOMÍA',
        website: 'https://www.uba.ar/',
      },
      {
        abbr: 'UNDL',
        name: 'UNIVERSIDAD NACIONAL DE LA MATANZA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'DERECHO, ARQUITECTURA, INGENIERÍA CIVIL, INGENIERÍA ELECTRÓNICA, INGENIERÍA INDUSTRIAL, INGENIERÍA MECÁNICA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y MARKETING, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, ADMINISTRACIÓN Y RECURSOS HUMANOS, CONTABILIDAD, ECONOMÍA, MEDICINA HUMANA, ENFERMERÍA, TECNOLOGÍA MÉDICA: TERAPIA FÍSICA Y REHABILITACIÓN',
        website: 'https://www.unlam.edu.ar/',
      },
      {
        abbr: 'UNDQ',
        name: 'UNIVERSIDAD NACIONAL DE QUILMES',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PRACTICAS / PASANTIAS',
        carrerasUC: 'DERECHO, CIENCIAS DE LA COMUNICACION, ARQUITECTURA, INGENIERÍA CIVIL, INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y MARKETING, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, ADMINISTRACIÓN Y RECURSOS HUMANOS, CONTABILIDAD, ECONOMÍA, ADMINISTRACIÓN Y GESTIÓN PÚBLICA, INGENIERÍA INDUSTRIAL, PSICOLOGÍA, CONTABILIDAD, ADMINISTRACIÓN',
        website: 'https://www.unq.edu.ar/',
      },
      {
        abbr: 'UNDM',
        name: 'UNIVERSIDAD NACIONAL DE MAR DEL PLATA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'DERECHO, PSICOLOGÍA, ARQUITECTURA, INGENIERÍA CIVIL, INGENIERÍA ELÉCTRICA, INGENIERÍA ELECTRÓNICA, INGENIERÍA INDUSTRIAL, INGENIERÍA MECÁNICA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, CONTABILIDAD, ECONOMÍA, MEDICINA HUMANA, ENFERMERÍA',
        website: 'https://www.mdp.edu.ar/',
      },
      {
        abbr: 'UTN',
        name: 'UNIVERSIDAD TECNOLÓGICA NACIONAL',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'INGENIERÍA AMBIENTAL, INGENIERÍA CIVIL, INGENIERÍA ELÉCTRICA, INGENIERÍA ELECTRÓNICA, INGENIERÍA EMPRESARIAL, INGENIERÍA INDUSTRIAL, INGENIERÍA MECÁNICA, INGENIERÍA MECATRÓNICA, INGENIERÍA DE MINAS, INGENIERÍA DE SISTEMAS',
        website: 'https://www.utn.edu.ar/es/',
      },
      {
        abbr: 'FESD',
        name: 'FUNDACIÓN ESCUELA SUPERIOR DE ECONOMÍA Y ADMINISTRACIÓN DE EMPRESAS (ESADE)',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y MARKETING, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, ADMINISTRACIÓN Y RECURSOS HUMANOS, CONTABILIDAD, ECONOMÍA',
        website: 'https://www.eseade.edu.ar/',
      },
      {
        abbr: 'UES2',
        name: 'UNIVERSIDAD EMPRESARIAL SIGLO 21',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'DERECHO, PSICOLOGÍA, INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, CONTABILIDAD, TECNOLOGÍA MÉDICA: TERAPIA FÍSICA Y REHABILITACIÓN, ADMINISTRACIÓN Y GESTIÓN PÚBLICA, CONTABILIDAD',
        website: 'https://21.edu.ar/',
      },
      {
        abbr: 'UNDG',
        name: 'UNIVERSIDAD NACIONAL DE GENERAL SAN MARTÍN',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'CIENCIAS DE LA COMUNICACION, PSICOLOGÍA, ARQUITECTURA, INGENIERÍA AMBIENTAL, INGENIERÍA CIVIL, INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, CONTABILIDAD, ECONOMÍA, MEDICINA HUMANA, ENFERMERÍA, CONTABILIDAD, ADMINISTRACIÓN',
        website: 'https://www.unsam.edu.ar/',
      },
      {
        abbr: 'UAI',
        name: 'UNIVERSIDAD ABIERTA INTERAMERICANA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'DERECHO, CIENCIAS DE LA COMUNICACION, PSICOLOGÍA, ARQUITECTURA, INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y MARKETING, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, CONTABILIDAD, ECONOMÍA, MEDICINA HUMANA, ODONTOLOGÍA, ENFERMERÍA, TECNOLOGÍA MÉDICA: TERAPIA FÍSICA Y REHABILITACIÓN, PSICOLOGÍA, CONTABILIDAD, ADMINISTRACIÓN',
        website: 'https://uai.edu.ar/',
      },
      {
        abbr: 'UNDC',
        name: 'UNIVERSIDAD NACIONAL DEL CUYO',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'DERECHO, PSICOLOGÍA, ARQUITECTURA, INGENIERÍA INDUSTRIAL, INGENIERÍA MECATRÓNICA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ECONOMÍA, MEDICINA HUMANA, ODONTOLOGÍA',
        website: 'https://www.uncuyo.edu.ar/',
      },
    ],
  },
  {
    flagCode: 'br',
    name: 'Brasil',
    programs: 'Intercambio estudiantil',
    institutions: 12,
    cities: '',
    photo:  '/images/Faculdade_de_Direito_do_Largo_de_Sao_Francisco.jpg',
    universities: [
      {
        abbr: 'EDC',
        name: 'ESCOLA DA CIDADE',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'ARQUITECTURA',
        website: 'https://escoladacidade.edu.br/',
      },
      {
        abbr: 'UP',
        name: 'UNIVERSIDAD PAULISTA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'DERECHO, CIENCIAS DE LA COMUNICACION, PSICOLOGÍA, ARQUITECTURA, INGENIERÍA AMBIENTAL, INGENIERÍA CIVIL, INGENIERÍA ELÉCTRICA, INGENIERÍA ELECTRÓNICA, INGENIERÍA INDUSTRIAL, INGENIERÍA MECÁNICA, INGENIERÍA MECATRÓNICA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y MARKETING, ADMINISTRACIÓN Y RECURSOS HUMANOS, CONTABILIDAD, ECONOMÍA, ODONTOLOGÍA, ENFERMERÍA, TECNOLOGÍA MÉDICA: TERAPIA FÍSICA Y REHABILITACIÓN',
        website: 'https://www.unip.br/',
      },
      {
        abbr: 'UFDM',
        name: 'UNIVERSIDAD FEDERAL DE MATO GROSSO',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'DERECHO, PSICOLOGÍA, ARQUITECTURA, INGENIERÍA AMBIENTAL, INGENIERÍA CIVIL, INGENIERÍA ELÉCTRICA, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, CONTABILIDAD, ECONOMÍA, ENFERMERÍA',
        website: 'https://www.ufmt.br/',
      },
      {
        abbr: 'CUSC',
        name: 'CENTRO UNIVERSITÁRIO SÃO CAMILO',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PRACTICAS / PASANTIAS, ROTACIONES MEDICAS',
        carrerasUC: 'PSICOLOGÍA, ADMINISTRACIÓN Y FINANZAS, MEDICINA HUMANA, ENFERMERÍA, TECNOLOGÍA MÉDICA: TERAPIA FÍSICA Y REHABILITACIÓN, RADIOLOGÍA',
        website: 'https://saocamilo-sp.br/',
      },
      {
        abbr: 'UEDL',
        name: 'UNIVERSIDAD ESTADUAL DE LONDRINA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PRACTICAS / PASANTIAS',
        carrerasUC: 'DERECHO, CIENCIAS DE LA COMUNICACION, PSICOLOGÍA, ARQUITECTURA, INGENIERÍA CIVIL, INGENIERÍA ELÉCTRICA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, CONTABILIDAD, ECONOMÍA, ODONTOLOGÍA, ENFERMERÍA, TECNOLOGÍA MÉDICA: TERAPIA FÍSICA Y REHABILITACIÓN',
        website: 'https://portal.uel.br/',
      },
      {
        abbr: 'UDSP',
        name: 'UNIVERSIDAD DE SAO PAULO',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PASANTIAS DE INVESTIGACION, PRACTICAS / PASANTIAS',
        carrerasUC: 'DERECHO, CIENCIAS DE LA COMUNICACION, PSICOLOGÍA, ARQUITECTURA, INGENIERÍA AMBIENTAL, INGENIERÍA CIVIL, INGENIERÍA ELÉCTRICA, INGENIERÍA ELECTRÓNICA, INGENIERÍA EMPRESARIAL, INGENIERÍA INDUSTRIAL, INGENIERÍA MECÁNICA, INGENIERÍA MECATRÓNICA, INGENIERÍA DE SISTEMAS, CONTABILIDAD, ECONOMÍA, MEDICINA HUMANA, ODONTOLOGÍA, ENFERMERÍA',
        website: 'https://www5.usp.br/',
      },
      {
        abbr: 'UDSC',
        name: 'UNIVERSIDADE DE SANTA CRUZ DO SUL',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PASANTIAS DE INVESTIGACION, PRACTICAS / PASANTIAS, MISIONES ACADEMICAS',
        carrerasUC: 'DERECHO, CIENCIAS DE LA COMUNICACION, PSICOLOGÍA, ARQUITECTURA, INGENIERÍA CIVIL, INGENIERÍA ELÉCTRICA, INGENIERÍA EMPRESARIAL, INGENIERÍA INDUSTRIAL, INGENIERÍA MECÁNICA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y MARKETING, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, ADMINISTRACIÓN Y RECURSOS HUMANOS, CONTABILIDAD',
        website: 'https://www.unisc.br/pt/',
      },
      {
        abbr: 'IBDE',
        name: 'INSTITUTO BRASILEIRO DE ENSINO',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'DERECHO, PSICOLOGÍA, INGENIERÍA AMBIENTAL, INGENIERÍA EMPRESARIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y MARKETING, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, ADMINISTRACIÓN Y RECURSOS HUMANOS, CONTABILIDAD, ADMINISTRACIÓN',
        website: 'https://www.idp.edu.br/',
      },
      {
        abbr: 'UEDG',
        name: 'UNIVERSIDADE EVANGÉLICA DE GOIÁS - UNIEVANGÉLICA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PASANTIAS DE INVESTIGACION, PRACTICAS / PASANTIAS',
        carrerasUC: 'DERECHO, PSICOLOGÍA, ARQUITECTURA, INGENIERÍA CIVIL, INGENIERÍA ELÉCTRICA, INGENIERÍA MECÁNICA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, CONTABILIDAD, MEDICINA HUMANA, ENFERMERÍA, TECNOLOGÍA MÉDICA: TERAPIA FÍSICA Y REHABILITACIÓN',
        website: 'https://www4.unievangelica.edu.br/',
      },
      {
        abbr: 'UCDP',
        name: 'UNIVERSIDADE CATÓLICA DO PARANÁ',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PASANTIAS DE INVESTIGACION, PRACTICAS / PASANTIAS, ROTACIONES MEDICAS',
        carrerasUC: 'DERECHO, CIENCIAS DE LA COMUNICACION, PSICOLOGÍA, ARQUITECTURA, INGENIERÍA CIVIL, INGENIERÍA ELÉCTRICA, INGENIERÍA INDUSTRIAL, INGENIERÍA MECATRÓNICA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y MARKETING, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, CONTABILIDAD, ECONOMÍA, MEDICINA HUMANA, ODONTOLOGÍA, ENFERMERÍA, TECNOLOGÍA MÉDICA: TERAPIA FÍSICA Y REHABILITACIÓN, PSICOLOGÍA, CONTABILIDAD, ADMINISTRACIÓN',
        website: 'https://www.pucpr.br/',
      },
      {
        abbr: 'IDM',
        name: 'INSTITUTO DE MAUÁ',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PRACTICAS / PASANTIAS',
        carrerasUC: 'INGENIERÍA CIVIL, INGENIERÍA ELÉCTRICA, INGENIERÍA ELECTRÓNICA, INGENIERÍA INDUSTRIAL, INGENIERÍA MECÁNICA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN',
        website: 'https://maua.br/',
      },
      {
        abbr: 'LUEP',
        name: 'LA UNIVERSIDADE ESTADUAL PAULISTA "JÚLIO DE MESQUITA FILHO" (UNESP)',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PASANTIAS DE INVESTIGACION, PRACTICAS / PASANTIAS, ROTACIONES MEDICAS',
        carrerasUC: 'DERECHO, PSICOLOGÍA, ARQUITECTURA, INGENIERÍA CIVIL, INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ECONOMÍA, MEDICINA HUMANA',
        website: 'https://www2.unesp.br/',
      },
    ],
  },
  {
    flagCode: 'co',
    name: 'Colombia',
    programs: 'Intercambio estudiantil',
    institutions: 32,
    cities: '',
    photo: '/images/UniandesBogota.jpg',
    universities: [
      {
        abbr: 'USA',
        name: 'UNIVERSIDAD SERGIO ARBOLEDA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, INTERCAMBIO SEMESTRAL VIRTUAL',
        carrerasUC: 'DERECHO, CIENCIAS DE LA COMUNICACION, PSICOLOGÍA, INGENIERÍA CIVIL, INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y MARKETING, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, CONTABILIDAD, ECONOMÍA',
        website: 'https://www.usergioarboleda.edu.co/',
      },
      {
        abbr: 'UADO',
        name: 'UNIVERSIDAD AUTÓNOMA DE OCCIDENTE',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'CIENCIAS DE LA COMUNICACION, PSICOLOGÍA, INGENIERÍA CIVIL, INGENIERÍA ELÉCTRICA, INGENIERÍA ELECTRÓNICA, INGENIERÍA INDUSTRIAL, INGENIERÍA MECÁNICA, INGENIERÍA MECATRÓNICA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y MARKETING, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, CONTABILIDAD, ECONOMÍA',
        website: 'https://www.uao.edu.co/',
      },
      {
        abbr: 'FUKL',
        name: 'FUNDACIÓN UNIVERSITARIA KONRAD LORENZ',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, INTERCAMBIO SEMESTRAL VIRTUAL',
        carrerasUC: 'CIENCIAS DE LA COMUNICACION, PSICOLOGÍA, INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y MARKETING, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES',
        website: 'https://www.konradlorenz.edu.co/',
      },
      {
        abbr: 'UDSB',
        name: 'UNIVERSIDAD DE SAN BUENAVENTURA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'DERECHO, PSICOLOGÍA, ARQUITECTURA, INGENIERÍA CIVIL, INGENIERÍA ELECTRÓNICA, INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, CONTABILIDAD',
        website: 'https://www.usbbog.edu.co/',
      },
      {
        abbr: 'UC',
        name: 'UNIVERSIDAD CENTRAL',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, INTERCAMBIO SEMESTRAL VIRTUAL, PASANTIAS DE INVESTIGACION',
        carrerasUC: 'CIENCIAS DE LA COMUNICACION, PSICOLOGÍA, INGENIERÍA CIVIL, INGENIERÍA ELÉCTRICA, INGENIERÍA INDUSTRIAL, INGENIERÍA MECÁNICA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, CONTABILIDAD, ECONOMÍA',
        website: 'https://www.ucentral.edu.co/',
      },
      {
        abbr: 'UDLC',
        name: 'UNIVERSIDAD DE LA COSTA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, INTERCAMBIO SEMESTRAL VIRTUAL, DOBLE TITULACION, MISIONES ACADEMICAS',
        carrerasUC: 'DERECHO, PSICOLOGÍA, ARQUITECTURA, INGENIERÍA AMBIENTAL, INGENIERÍA CIVIL, INGENIERÍA ELÉCTRICA, INGENIERÍA ELECTRÓNICA, INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y MARKETING, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, CONTABILIDAD',
        website: 'https://www.cuc.edu.co/',
      },
      {
        abbr: 'UAL',
        name: 'UNIVERSIDAD AUTÓNOMA LATINOAMERICANA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'DERECHO, INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, CONTABILIDAD, ECONOMÍA',
        website: 'https://www.unaula.edu.co/',
      },
      {
        abbr: 'UDIY',
        name: 'UNIVERSIDAD DE INVESTIGACION Y DESARROLLO',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, INTERCAMBIO SEMESTRAL VIRTUAL, PASANTIAS DE INVESTIGACION',
        carrerasUC: 'DERECHO, CIENCIAS DE LA COMUNICACION, PSICOLOGÍA, INGENIERÍA CIVIL, INGENIERÍA ELECTRÓNICA, INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, CONTABILIDAD',
        website: 'https://web.udi.edu.co/',
      },
      {
        abbr: 'UDA',
        name: 'UNIVERSIDAD DE ANTIOQUIA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PASANTIAS DE INVESTIGACION, PRACTICAS / PASANTIAS, MISIONES ACADEMICAS',
        carrerasUC: 'DERECHO, PSICOLOGÍA, INGENIERÍA CIVIL, INGENIERÍA ELÉCTRICA, INGENIERÍA INDUSTRIAL, INGENIERÍA MECÁNICA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, CONTABILIDAD, ECONOMÍA, MEDICINA HUMANA, ODONTOLOGÍA, ENFERMERÍA',
        website: 'https://www.udea.edu.co/wps/portal/udea/web/inicio',
      },
      {
        abbr: 'FUDÁ',
        name: 'FUNDACIÓN UNIVERSITARIA DEL ÁREA ANDINA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, INTERCAMBIO SEMESTRAL VIRTUAL, PASANTIAS DE INVESTIGACION, PRACTICAS / PASANTIAS, ROTACIONES MEDICAS, MISIONES ACADEMICAS',
        carrerasUC: 'MEDICINA HUMANA, ODONTOLOGÍA, ENFERMERÍA, TECNOLOGÍA MÉDICA:LABORATORIO CLÍNICO Y ANATOMÍA, TECNOLOGÍA MÉDICA: TERAPIA FÍSICA Y REHABILITACIÓN, RADIOLOGÍA',
        website: 'https://www.areandina.edu.co/',
      },
      {
        abbr: 'UDI',
        name: 'UNIVERSIDAD DE IBAGUÉ',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PRACTICAS / PASANTIAS',
        carrerasUC: 'DERECHO, CIENCIAS DE LA COMUNICACION, PSICOLOGÍA, ARQUITECTURA, INGENIERÍA CIVIL, INGENIERÍA ELECTRÓNICA, INGENIERÍA INDUSTRIAL, INGENIERÍA MECÁNICA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y MARKETING, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, CONTABILIDAD, ECONOMÍA',
        website: 'https://www.unibague.edu.co/',
      },
      {
        abbr: 'UDN',
        name: 'UNIVERSIDAD DE NARIÑO',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, INTERCAMBIO SEMESTRAL VIRTUAL',
        carrerasUC: 'ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y MARKETING, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, ADMINISTRACIÓN Y RECURSOS HUMANOS',
        website: 'https://www.udenar.edu.co/',
      },
      {
        abbr: 'UDLA',
        name: 'UNIVERSIDAD DE LOS ANDES',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PRACTICAS / PASANTIAS, ROTACIONES MEDICAS, MISIONES ACADEMICAS',
        carrerasUC: 'ARQUITECTURA, INGENIERÍA CIVIL, INGENIERÍA ELÉCTRICA, INGENIERÍA INDUSTRIAL, INGENIERÍA MECÁNICA, INGENIERÍA DE SISTEMAS, MEDICINA HUMANA, ENFERMERÍA',
        website: 'https://www.uniandes.edu.co/',
      },
      {
        abbr: 'FUJN',
        name: 'FUNDACIÓN UNIVERSITARIA JUAN N. CORPAS',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PRACTICAS / PASANTIAS, ROTACIONES MEDICAS, MISIONES ACADEMICAS',
        carrerasUC: 'MEDICINA HUMANA, ENFERMERÍA',
        website: 'https://www.juanncorpas.edu.co/',
      },
      {
        abbr: 'UPYT',
        name: 'UNIVERSIDAD PEDAGÓGICA Y TECNOLÓGICA DE COLOMBIA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'DERECHO, PSICOLOGÍA, INGENIERÍA CIVIL, INGENIERÍA ELECTRÓNICA, INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, CONTABILIDAD, ECONOMÍA, MEDICINA HUMANA, ENFERMERÍA',
        website: 'https://www.uptc.edu.co/',
      },
      {
        abbr: 'UDS',
        name: 'UNIVERSIDAD DE SANTANDER',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, INTERCAMBIO SEMESTRAL VIRTUAL, PASANTIAS DE INVESTIGACION, PRACTICAS / PASANTIAS, ROTACIONES MEDICAS, MISIONES ACADEMICAS',
        carrerasUC: 'DERECHO, PSICOLOGÍA, INGENIERÍA CIVIL, INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y MARKETING, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, CONTABILIDAD, MEDICINA HUMANA, ODONTOLOGÍA, TECNOLOGÍA MÉDICA:LABORATORIO CLÍNICO Y ANATOMÍA, TECNOLOGÍA MÉDICA: TERAPIA FÍSICA Y REHABILITACIÓN',
        website: 'https://udes.edu.co/',
      },
      {
        abbr: 'HUDL',
        name: 'HOSPITAL UNIVERSITARIO DE LA SAMARITANA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PRACTICAS / PASANTIAS, ROTACIONES MEDICAS',
        carrerasUC: 'MEDICINA HUMANA, ENFERMERÍA',
        website: 'https://www.hus.org.co/',
      },
      {
        abbr: 'CUAD',
        name: 'CORPORACIÓN UNIVERSITARIA AUTÓNOMA DE NARIÑO',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PRACTICAS / PASANTIAS',
        carrerasUC: 'DERECHO, INGENIERÍA ELECTRÓNICA, INGENIERÍA MECÁNICA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, CONTABILIDAD, CONTABILIDAD, ADMINISTRACIÓN',
        website: 'https://www.aunar.edu.co/',
      },
      {
        abbr: 'IUE',
        name: 'INSTITUCIÓN UNIVERSITARIA ESUMER',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PASANTIAS DE INVESTIGACION, PRACTICAS / PASANTIAS',
        carrerasUC: 'ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES',
        website: 'https://esumer.edu.co/',
      },
      {
        abbr: 'CURN',
        name: 'CORPORACION UNIVERSITARIA RAFAEL NÚÑEZ',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'DERECHO, INGENIERÍA DE SISTEMAS, CONTABILIDAD, MEDICINA HUMANA, ODONTOLOGÍA, ENFERMERÍA',
        website: 'https://www.uninunez.edu.co/',
      },
      {
        abbr: 'UAN',
        name: 'UNIVERSIDAD ANTONIO NARIÑO',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, INTERCAMBIO SEMESTRAL VIRTUAL',
        carrerasUC: 'ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y MARKETING, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, ADMINISTRACIÓN Y RECURSOS HUMANOS',
        website: 'https://www.uan.edu.co/',
      },
      {
        abbr: 'CPDL',
        name: 'CORPORACION POLITÉCNICO DE LA COSTA ATLÁNTICA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, CONTABILIDAD',
        website: 'https://pca.edu.co/wp/',
      },
      {
        abbr: 'UDFJ',
        name: 'UNIVERSIDAD DISTRITAL FRANCISCO JOSE DE CALDAS',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, ROTACIONES MEDICAS',
        carrerasUC: 'INGENIERÍA CIVIL, INGENIERÍA ELÉCTRICA, INGENIERÍA ELECTRÓNICA, INGENIERÍA INDUSTRIAL, INGENIERÍA MECÁNICA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y MARKETING, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, ADMINISTRACIÓN Y RECURSOS HUMANOS',
        website: 'https://www.udistrital.edu.co/inicio',
      },
      {
        abbr: 'UDLG',
        name: 'UNIVERSIDAD DE LA GUAJIRA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PASANTIAS DE INVESTIGACION, PRACTICAS / PASANTIAS',
        carrerasUC: 'DERECHO, PSICOLOGÍA, INGENIERÍA CIVIL, INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y MARKETING, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, CONTABILIDAD, ECONOMÍA, ADMINISTRACIÓN Y GESTIÓN PÚBLICA, INGENIERÍA INDUSTRIAL, ADMINISTRACIÓN',
        website: 'https://uniguajira.edu.co/',
      },
      {
        abbr: 'IUDD',
        name: 'INSTITUCIÓN UNIVERSITARIA DIGITAL DE ANTIOQUIA –LA IU DIGITAL',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PRACTICAS / PASANTIAS',
        carrerasUC: 'INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y MARKETING, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, ADMINISTRACIÓN Y RECURSOS HUMANOS, ADMINISTRACIÓN',
        website: 'https://www.iudigital.edu.co/',
      },
      {
        abbr: 'CUA',
        name: 'CORPORACIÓN UNIVERSITARIA AMERICANA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PRACTICAS / PASANTIAS',
        carrerasUC: 'DERECHO, PSICOLOGÍA, INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y MARKETING, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, CONTABILIDAD, INGENIERÍA INDUSTRIAL, PSICOLOGÍA, CONTABILIDAD, ADMINISTRACIÓN',
        website: 'https://americana.edu.co/',
      },
      {
        abbr: 'UADB',
        name: 'UNIVERSIDAD AUTÓNOMA DE BUCARAMANGA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, INTERCAMBIO SEMESTRAL VIRTUAL, PRACTICAS / PASANTIAS, ROTACIONES MEDICAS',
        carrerasUC: 'INGENIERÍA EMPRESARIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y MARKETING, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, CONTABILIDAD, ECONOMÍA, INGENIERÍA INDUSTRIAL, PSICOLOGÍA, CONTABILIDAD, ADMINISTRACIÓN',
        website: 'https://unab.edu.co/',
      },
      {
        abbr: 'FUSM',
        name: 'FUNDACIÓN UNIVERSITARIA SAN MARTÍN',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PRACTICAS / PASANTIAS, ROTACIONES MEDICAS',
        carrerasUC: 'DERECHO, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y MARKETING, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, CONTABILIDAD, MEDICINA HUMANA, ODONTOLOGÍA, CONTABILIDAD, ADMINISTRACIÓN',
        website: 'https://sanmartin.edu.co/',
      },
      {
        abbr: 'UNDC',
        name: 'UNIVERDSIDAD NACIONAL DE COLOMBIA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'DERECHO, PSICOLOGÍA, ARQUITECTURA, INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, CONTABILIDAD, MEDICINA HUMANA, ODONTOLOGÍA',
        website: 'https://unal.edu.co/',
      },
      {
        abbr: 'UEB',
        name: 'UNIVERSIDAD EL BOSQUE',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, INTERCAMBIO SEMESTRAL VIRTUAL',
        carrerasUC: 'DERECHO, PSICOLOGÍA, ARQUITECTURA, INGENIERÍA ELECTRÓNICA, INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, MEDICINA HUMANA, ODONTOLOGÍA',
        website: 'https://www.unbosque.edu.co/',
      },
      {
        abbr: 'UCDC',
        name: 'UNIVERSIDAD COOPERATIVA DE COLOMBIA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'DERECHO, PSICOLOGÍA, INGENIERÍA CIVIL, INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, CONTABILIDAD, MEDICINA HUMANA, ODONTOLOGÍA',
        website: 'https://www.ucc.edu.co/',
      },
      {
        abbr: 'UST',
        name: 'UNIVERSIDAD SANTO TOMÁS',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, INTERCAMBIO SEMESTRAL VIRTUAL, PRACTICAS / PASANTIAS, ROTACIONES MEDICAS',
        carrerasUC: 'DERECHO, PSICOLOGÍA, ARQUITECTURA, INGENIERÍA CIVIL, INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, CONTABILIDAD',
        website: 'https://usantotomas.edu.co/inicio',
      },
    ],
  },
  {
    flagCode: 'cl',
    name: 'Chile',
    programs: 'Intercambio estudiantil',
    institutions: 7,
    cities: '',
    photo: '/images/Chile.jpg',
    universities: [
      {
        abbr: 'UAB',
        name: 'UNIVERSIDAD ANDRÉS BELLO',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'DERECHO, PSICOLOGÍA, ARQUITECTURA, INGENIERÍA CIVIL, INGENIERÍA INDUSTRIAL, INGENIERÍA DE MINAS, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, CONTABILIDAD, MEDICINA HUMANA, ODONTOLOGÍA, ENFERMERÍA, TECNOLOGÍA MÉDICA:LABORATORIO CLÍNICO Y ANATOMÍA, TECNOLOGÍA MÉDICA: TERAPIA FÍSICA Y REHABILITACIÓN',
        website: 'https://www.unab.cl/',
      },
      {
        abbr: 'UC',
        name: 'UNIVERSIDAD CENTRAL',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, INTERCAMBIO SEMESTRAL VIRTUAL',
        carrerasUC: 'DERECHO, CIENCIAS DE LA COMUNICACION, PSICOLOGÍA, ARQUITECTURA, INGENIERÍA CIVIL, INGENIERÍA INDUSTRIAL, INGENIERÍA DE MINAS, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y MARKETING, CONTABILIDAD, ENFERMERÍA, TECNOLOGÍA MÉDICA:LABORATORIO CLÍNICO Y ANATOMÍA, TECNOLOGÍA MÉDICA: TERAPIA FÍSICA Y REHABILITACIÓN',
        website: 'https://www.ucentral.cl/',
      },
      {
        abbr: 'USS',
        name: 'UNIVERSIDAD SAN SEBASTIÁN',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'DERECHO, PSICOLOGÍA, ARQUITECTURA, INGENIERÍA CIVIL, INGENIERÍA DE MINAS, INGENIERÍA DE SISTEMAS, MEDICINA HUMANA, ODONTOLOGÍA, ENFERMERÍA, TECNOLOGÍA MÉDICA:LABORATORIO CLÍNICO Y ANATOMÍA',
        website: 'https://www.uss.cl/',
      },
      {
        abbr: 'UCDN',
        name: 'UNIVERSIDAD CATÓLICA DEL NORTE DE CHILE',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PRACTICAS / PASANTIAS',
        carrerasUC: 'DERECHO, PSICOLOGÍA, ARQUITECTURA, INGENIERÍA CIVIL, INGENIERÍA INDUSTRIAL, INGENIERÍA DE MINAS, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y MARKETING, CONTABILIDAD, MEDICINA HUMANA, ENFERMERÍA',
        website: 'https://www.ucn.cl/',
      },
      {
        abbr: 'UDC',
        name: 'UNIVERSIDAD DE CHILE',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PASANTIAS DE INVESTIGACION, PRACTICAS / PASANTIAS',
        carrerasUC: 'DERECHO, CIENCIAS DE LA COMUNICACION, ARQUITECTURA, INGENIERÍA DE MINAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, MEDICINA HUMANA, ENFERMERÍA',
        website: 'https://uchile.cl/',
      },
      {
        abbr: 'UCDV',
        name: 'UNIVERSIDAD CATÓLICA DEL VALPARAÍSO',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'DERECHO, CIENCIAS DE LA COMUNICACION, PSICOLOGÍA, ARQUITECTURA, INGENIERÍA CIVIL, INGENIERÍA ELÉCTRICA, INGENIERÍA ELECTRÓNICA, INGENIERÍA INDUSTRIAL, INGENIERÍA MECÁNICA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y MARKETING, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, ADMINISTRACIÓN Y RECURSOS HUMANOS, CONTABILIDAD, ECONOMÍA, TECNOLOGÍA MÉDICA:LABORATORIO CLÍNICO Y ANATOMÍA, TECNOLOGÍA MÉDICA: TERAPIA FÍSICA Y REHABILITACIÓN, ADMINISTRACIÓN Y GESTIÓN PÚBLICA, INGENIERÍA INDUSTRIAL, PSICOLOGÍA, CONTABILIDAD, ADMINISTRACIÓN',
        website: 'https://www.pucv.cl/',
      },
      {
        abbr: 'UFT',
        name: 'UNIVERSIDAD FINIS TERRAE',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'DERECHO, PSICOLOGÍA, ARQUITECTURA, INGENIERÍA EMPRESARIAL, INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, MEDICINA HUMANA, ODONTOLOGÍA',
        website: 'https://finis.cl/',
      },
    ],
  },
  {
    flagCode: 'gt',
    name: 'Guatemala',
    programs: 'Intercambio estudiantil',
    institutions: 1,
    cities: '',
    photo: '/images/Guatemala.jpg',
    universities: [
      {
        abbr: 'UG',
        name: 'UNIVERSIDAD GALILEO',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PASANTIAS DE INVESTIGACION',
        carrerasUC: 'CIENCIAS DE LA COMUNICACION, ARQUITECTURA, INGENIERÍA CIVIL, INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ENFERMERÍA, TECNOLOGÍA MÉDICA: TERAPIA FÍSICA Y REHABILITACIÓN, INGENIERÍA INDUSTRIAL, ADMINISTRACIÓN',
        website: 'https://www.galileo.edu/',
      },
    ],
  },
  {
    flagCode: 'mx',
    name: 'México',
    programs: 'Intercambio estudiantil',
    institutions: 29,
    cities: '',
    photo:  '/images/mexicocapital.jpg',
    universities: [
      {
        abbr: 'UTDH',
        name: 'UNIVERSIDAD TECNOLÓGICA DE HUEJOTZINGO',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PASANTIAS DE INVESTIGACION',
        carrerasUC: 'INGENIERÍA INDUSTRIAL, INGENIERÍA MECATRÓNICA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y MARKETING',
        website: 'https://www.uth.edu.mx/',
      },
      {
        abbr: 'UPDT',
        name: 'UNIVERSIDAD POLITÉCNICA DE TULANCINGO',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'INGENIERÍA CIVIL, INGENIERÍA INDUSTRIAL, INGENIERÍA MECÁNICA, INGENIERÍA MECATRÓNICA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES',
        website: 'https://www.upt.edu.mx/',
      },
      {
        abbr: 'UTDC',
        name: 'UNIVERSIDAD TECNOLÓGICA DE CANCÚN',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'INGENIERÍA INDUSTRIAL, INGENIERÍA MECÁNICA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, CONTABILIDAD',
        website: 'https://utcancun.edu.mx/',
      },
      {
        abbr: 'UPDT',
        name: 'UNIVERSIDAD POLITÉCNICA DE TLAXCALA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'INGENIERÍA INDUSTRIAL, INGENIERÍA MECATRÓNICA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS',
        website: 'https://uptlax.edu.mx/',
      },
      {
        abbr: 'UTDT',
        name: 'UNIVERSIDAD TECNOLÓGICA DE TLAXCALA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'INGENIERÍA INDUSTRIAL, INGENIERÍA MECÁNICA, INGENIERÍA MECATRÓNICA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y MARKETING',
        website: 'https://www.uttlaxcala.edu.mx/',
      },
      {
        abbr: 'UDVD',
        name: 'UNIVERSIDAD DEL VALLE DE ATEMAJAC',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PASANTIAS DE INVESTIGACION, PRACTICAS / PASANTIAS',
        carrerasUC: 'DERECHO, PSICOLOGÍA, ARQUITECTURA, INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, CONTABILIDAD, MEDICINA HUMANA',
        website: 'https://www.univa.mx/',
      },
      {
        abbr: 'UTDS',
        name: 'UNIVERSIDAD TECNOLÓGIA DE SALAMANCA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'INGENIERÍA AMBIENTAL, INGENIERÍA INDUSTRIAL, INGENIERÍA MECÁNICA, INGENIERÍA MECATRÓNICA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES',
        website: 'https://www.utsalamanca.edu.mx/',
      },
      {
        abbr: 'UTDL',
        name: 'UNIVERSIDAD TECNOLOGICA DE LOS VALLES CENTRALES DE OAXACA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PASANTIAS DE INVESTIGACION',
        carrerasUC: 'INGENIERÍA AMBIENTAL, INGENIERÍA MECATRÓNICA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES',
        website: 'https://utvco.edu.mx/',
      },
      {
        abbr: 'UPMD',
        name: 'UNIVERSIDAD POLITÉCNICA METROPOLITANA DE HIDALGO',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, INTERCAMBIO SEMESTRAL VIRTUAL',
        carrerasUC: 'CIENCIAS DE LA COMUNICACION, INGENIERÍA ELÉCTRICA, INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, INGENIERÍA INDUSTRIAL',
        website: 'https://www.upmh.edu.mx/',
      },
      {
        abbr: 'UAM',
        name: 'UNIVERSIDAD AUTÓNOMA METROPOLITANA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, INTERCAMBIO SEMESTRAL VIRTUAL',
        carrerasUC: 'DERECHO, PSICOLOGÍA, ARQUITECTURA, INGENIERÍA AMBIENTAL, INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ECONOMÍA, MEDICINA HUMANA, ENFERMERÍA, INGENIERÍA INDUSTRIAL, PSICOLOGÍA, ADMINISTRACIÓN',
        website: 'https://www.uam.mx/',
      },
      {
        abbr: 'UPDA',
        name: 'UNIVERSIDAD POLITÉCNICA DE ATLAUTLA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PRACTICAS / PASANTIAS',
        carrerasUC: 'INGENIERÍA CIVIL, INGENIERÍA INDUSTRIAL, INGENIERÍA MECÁNICA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS',
        website: 'https://upa.edomex.gob.mx/',
      },
      {
        abbr: 'ITSD',
        name: 'INSTITUTO TECNOLÓGICO SUPERIOR DEL ORIENTE ESTADO DE HIDALGO',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'INGENIERÍA CIVIL, INGENIERÍA ELÉCTRICA, INGENIERÍA INDUSTRIAL, INGENIERÍA MECÁNICA, INGENIERÍA MECATRÓNICA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS',
        website: 'https://www.itesa.edu.mx/',
      },
      {
        abbr: 'UDG',
        name: 'UNIVERSIDAD DE GUADALAJARA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'DERECHO, PSICOLOGÍA, ARQUITECTURA, INGENIERÍA CIVIL, INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, CONTABILIDAD, MEDICINA HUMANA, ENFERMERÍA',
        website: 'https://www.udg.mx/',
      },
      {
        abbr: 'UNAD',
        name: 'UNIVERSIDAD NACIONAL AUTÓNOMA DE MÉXICO - UNAM',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, INTERCAMBIO SEMESTRAL VIRTUAL, PRACTICAS / PASANTIAS, ROTACIONES MEDICAS',
        carrerasUC: 'DERECHO, PSICOLOGÍA, ARQUITECTURA, INGENIERÍA CIVIL, INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, CONTABILIDAD, MEDICINA HUMANA, INGENIERÍA INDUSTRIAL, PSICOLOGÍA, CONTABILIDAD, ADMINISTRACIÓN',
        website: 'https://www.unam.mx/',
      },
      {
        abbr: 'ANDU',
        name: 'ASOCIACIÓN NACIONAL DE UNIVERSIDADES TECNOLÓGICAS-ANUT',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, INTERCAMBIO SEMESTRAL VIRTUAL, PASANTIAS DE INVESTIGACION',
        carrerasUC: 'INGENIERÍA AMBIENTAL, INGENIERÍA CIVIL, INGENIERÍA ELÉCTRICA, INGENIERÍA ELECTRÓNICA, INGENIERÍA EMPRESARIAL, INGENIERÍA INDUSTRIAL, INGENIERÍA MECÁNICA, INGENIERÍA MECATRÓNICA, INGENIERÍA DE MINAS, INGENIERÍA DE SISTEMAS',
        website: '',
      },
      {
        abbr: 'BUAD',
        name: 'BENEMÉRITA UNIVERSIDAD AUTÓNOMA DE PUEBLA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'DERECHO, PSICOLOGÍA, ARQUITECTURA, INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, CONTABILIDAD, MEDICINA HUMANA, ENFERMERÍA',
        website: 'https://www.buap.mx/',
      },
      {
        abbr: 'UPAD',
        name: 'UNIVERSIDAD POPULAR AUTÓNOMA DEL ESTADO DE PUEBLA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'DERECHO, PSICOLOGÍA, ARQUITECTURA, INGENIERÍA INDUSTRIAL, INGENIERÍA MECATRÓNICA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, MEDICINA HUMANA, ODONTOLOGÍA',
        website: 'https://www.upaep.mx/',
      },
      {
        abbr: 'UTDV',
        name: 'UNIVERSIDAD TECNOLÓGICA DEL VALLE DE MEZQUITAL',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'INGENIERÍA AMBIENTAL, INGENIERÍA INDUSTRIAL, INGENIERÍA MECATRÓNICA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS',
        website: 'https://www.utvm.edu.mx/',
      },
      {
        abbr: 'UQR',
        name: 'UNIVERSIDAD QUINTANA ROO',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'DERECHO, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES',
        website: 'https://www.uqroo.mx/',
      },
      {
        abbr: 'UADS',
        name: 'UNIVERSIDAD AUTÓNOMA DE SINALOA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PRACTICAS / PASANTIAS',
        carrerasUC: 'DERECHO, PSICOLOGÍA, ARQUITECTURA, INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, CONTABILIDAD, MEDICINA HUMANA',
        website: 'https://www.uas.edu.mx/',
      },
      {
        abbr: 'UADB',
        name: 'UNIVERSIDAD AUTÓNOMA DE BAJA CALIFORNIA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'DERECHO, PSICOLOGÍA, ARQUITECTURA, INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, CONTABILIDAD, MEDICINA HUMANA, ODONTOLOGÍA',
        website: 'https://www.uabc.mx/',
      },
      {
        abbr: 'UDM',
        name: 'UNIVERSIDAD DE MONTERREY',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PASANTIAS DE INVESTIGACION, PRACTICAS / PASANTIAS, ROTACIONES MEDICAS',
        carrerasUC: 'MEDICINA HUMANA, ODONTOLOGÍA, ENFERMERÍA, TECNOLOGÍA MÉDICA:LABORATORIO CLÍNICO Y ANATOMÍA, TECNOLOGÍA MÉDICA: TERAPIA FÍSICA Y REHABILITACIÓN',
        website: 'https://www.udem.edu.mx/es',
      },
      {
        abbr: 'UTDS',
        name: 'UNIVERSIDAD TECNOLÓGICA DE SAN JUAN DEL RÍO (UTSJR)',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'INGENIERÍA AMBIENTAL, INGENIERÍA INDUSTRIAL, INGENIERÍA MECÁNICA, INGENIERÍA MECATRÓNICA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y MARKETING',
        website: 'https://www.utsjr.edu.mx/',
      },
      {
        abbr: 'UDLS',
        name: 'UNIVERSIDAD DE LA SALLE BAJÍO',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PASANTIAS DE INVESTIGACION',
        carrerasUC: 'DERECHO, ARQUITECTURA, INGENIERÍA INDUSTRIAL, INGENIERÍA MECATRÓNICA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, CONTABILIDAD, MEDICINA HUMANA, ODONTOLOGÍA',
        website: 'https://www.lasallebajio.edu.mx/',
      },
      {
        abbr: 'UADQ',
        name: 'UNIVERSIDAD AUTÓNOMA DE QUERÉTANO',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'DERECHO, PSICOLOGÍA, INGENIERÍA CIVIL, INGENIERÍA INDUSTRIAL, INGENIERÍA MECATRÓNICA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, CONTABILIDAD, MEDICINA HUMANA, ENFERMERÍA',
        website: 'https://www.uaq.mx/',
      },
      {
        abbr: 'UTDM',
        name: 'UNIVERSIDAD TENCOLÓGICA DE MINERAL DE LA REFORMA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'INGENIERÍA AMBIENTAL, INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y RECURSOS HUMANOS, ADMINISTRACIÓN',
        website: 'https://www.utmir.edu.mx/',
      },
      {
        abbr: 'UPDA',
        name: 'UNIVERSIDAD POLITÉCNICA DE ATLAUTLA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'INGENIERÍA CIVIL, INGENIERÍA ELECTRÓNICA, INGENIERÍA MECATRÓNICA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN',
        website: 'https://upa.edomex.gob.mx/',
      },
      {
        abbr: 'UTDM',
        name: 'UNIVERSIDAD TECNOLOGICA DEL MAR DEL ESTADO DE GUERRERO',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PASANTIAS DE INVESTIGACION, PRACTICAS / PASANTIAS',
        carrerasUC: 'INGENIERÍA AMBIENTAL, INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN',
        website: 'https://utmarguerrero.edu.mx/',
      },
      {
        abbr: 'ITYD',
        name: 'INSTITUTO TECNOLÓGICO Y DE ESTUDIOS SUPERIORES DE MONTERREY',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'ROTACIONES MEDICAS',
        carrerasUC: 'PSICOLOGÍA, MEDICINA HUMANA, ENFERMERÍA',
        website: 'https://tec.mx/es',
      },
    ],
  },
  {
    flagCode: 'cr',
    name: 'Costa Rica',
    programs: 'Intercambio estudiantil',
    institutions: 1,
    cities: '',
    photo: 'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=900&q=80',
    universities: [
      {
        abbr: 'UIDL',
        name: 'UNIVERSIDAD INTERNACIONAL DE LAS AMÉRICAS',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'DERECHO, CIENCIAS DE LA COMUNICACION, INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y MARKETING, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, ADMINISTRACIÓN Y RECURSOS HUMANOS, CONTABILIDAD, ECONOMÍA, MEDICINA HUMANA, ODONTOLOGÍA',
        website: 'https://uia.ac.cr/',
      },
    ],
  },
  {
    flagCode: 'py',
    name: 'Paraguay',
    programs: 'Intercambio estudiantil',
    institutions: 5,
    cities: '',
    photo: 'https://images.unsplash.com/photo-1605640840605-14ac1855827b?w=900&q=80',
    universities: [
      {
        abbr: 'UA',
        name: 'UNIVERSIDAD AMERICANA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, INTERCAMBIO SEMESTRAL VIRTUAL',
        carrerasUC: 'DERECHO, PSICOLOGÍA, ARQUITECTURA, INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y MARKETING, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, MEDICINA HUMANA, ODONTOLOGÍA, INGENIERÍA INDUSTRIAL, PSICOLOGÍA, ADMINISTRACIÓN',
        website: 'https://www.americana.edu.py/',
      },
      {
        abbr: 'UDN',
        name: 'UNIVERSIDAD DEL NORTE',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, INTERCAMBIO SEMESTRAL VIRTUAL, ROTACIONES MEDICAS',
        carrerasUC: 'DERECHO, PSICOLOGÍA, ARQUITECTURA, INGENIERÍA EMPRESARIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, CONTABILIDAD, MEDICINA HUMANA, ODONTOLOGÍA, ENFERMERÍA, PSICOLOGÍA, CONTABILIDAD, ADMINISTRACIÓN',
        website: 'https://uninorte.edu.py/',
      },
      {
        abbr: 'PTI',
        name: 'PARQUE TECNOLÓGICO ITAPU',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, INTERCAMBIO SEMESTRAL VIRTUAL, PASANTIAS DE INVESTIGACION, MISIONES ACADEMICAS',
        carrerasUC: 'ARQUITECTURA, INGENIERÍA AMBIENTAL, INGENIERÍA CIVIL, INGENIERÍA ELÉCTRICA, INGENIERÍA MECATRÓNICA, INGENIERÍA DE SISTEMAS',
        website: 'https://www.pti.org.py/',
      },
      {
        abbr: 'US',
        name: 'UNIVERSIDAD SUDAMERICANA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PASANTIAS DE INVESTIGACION, PRACTICAS / PASANTIAS, ROTACIONES MEDICAS',
        carrerasUC: 'MEDICINA HUMANA, ODONTOLOGÍA, ENFERMERÍA, TECNOLOGÍA MÉDICA:LABORATORIO CLÍNICO Y ANATOMÍA, TECNOLOGÍA MÉDICA: TERAPIA FÍSICA Y REHABILITACIÓN, RADIOLOGÍA, ADMINISTRACIÓN',
        website: 'https://www.unisud.edu.py/',
      },
      {
        abbr: 'USLU',
        name: 'UNIVERSIDAD SAN LORENZO (USAL)',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PASANTIAS DE INVESTIGACION, PRACTICAS / PASANTIAS',
        carrerasUC: 'DERECHO, ARQUITECTURA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, CONTABILIDAD, ENFERMERÍA, CONTABILIDAD, ADMINISTRACIÓN',
        website: 'https://unisal.edu.py/',
      },
    ],
  },
  {
    flagCode: 'es',
    name: 'España',
    programs: 'Intercambio estudiantil',
    institutions: 16,
    cities: '',
    photo:'/images/España.jpg',
    universities: [
      {
        abbr: 'UDV',
        name: 'UNIVERSIDAD DE VALLADOLID',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: '',
        carrerasUC: 'ARQUITECTURA, INGENIERÍA ELÉCTRICA, INGENIERÍA MECÁNICA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y MARKETING, ECONOMÍA, MEDICINA HUMANA, ENFERMERÍA',
        website: 'https://www.uva.es/export/sites/uva/',
      },
      {
        abbr: 'E',
        name: 'Euroespes',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'PASANTIAS DE INVESTIGACION, PRACTICAS / PASANTIAS',
        carrerasUC: 'MEDICINA HUMANA, ENFERMERÍA, TECNOLOGÍA MÉDICA: TERAPIA FÍSICA Y REHABILITACIÓN',
        website: 'https://euroespes.com/',
      },
      {
        abbr: 'UPDO',
        name: 'UNIVERSIDAD PABLO DE OLAVIDE',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: '',
        carrerasUC: 'DERECHO, PSICOLOGÍA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, CONTABILIDAD, MEDICINA HUMANA, TECNOLOGÍA MÉDICA: TERAPIA FÍSICA Y REHABILITACIÓN',
        website: 'https://www.upo.es/portal/impe/web/portada/index.html',
      },
      {
        abbr: 'URIV',
        name: 'UNIVERSITAT ROVIRA I VIRGILI',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'DERECHO, PSICOLOGÍA, INGENIERÍA ELÉCTRICA, INGENIERÍA MECÁNICA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, CONTABILIDAD, MEDICINA HUMANA',
        website: 'https://www.urv.cat/ca/',
      },
      {
        abbr: 'UADC',
        name: 'UNIVERSIDAD ABIERTA DE CATALUÑA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL VIRTUAL',
        carrerasUC: 'DERECHO, PSICOLOGÍA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y GESTIÓN PÚBLICA',
        website: 'https://www.uoc.edu/es',
      },
      {
        abbr: 'FUDB',
        name: 'FUNDACIÓN UNIVERSITARIA DEL BAGES-UMANRESA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: '',
        carrerasUC: 'ADMINISTRACIÓN Y FINANZAS, MEDICINA HUMANA, ENFERMERÍA, TECNOLOGÍA MÉDICA: TERAPIA FÍSICA Y REHABILITACIÓN',
        website: 'https://www.umanresa.cat/',
      },
      {
        abbr: 'ISDE',
        name: 'INSTITUTOS SUPERIORES DE ESTUDIOS PSICOLÓGICOS - ISEP',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'PSICOLOGÍA, ADMINISTRACIÓN Y RECURSOS HUMANOS, CONTABILIDAD',
        website: 'https://www.isep.es/',
      },
      {
        abbr: 'EBSA',
        name: 'EUNCENT BUSINESS SCHOOL - Afiliada a la U. Politécnica de Cataluña',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: '',
        carrerasUC: 'CIENCIAS DE LA COMUNICACION, INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y MARKETING',
        website: 'https://www.euncet.com/es/',
      },
      {
        abbr: 'UPDM',
        name: 'UNIVERSIDAD POLITECNICA DE MADRID',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PASANTIAS DE INVESTIGACION, PRACTICAS / PASANTIAS',
        carrerasUC: 'ARQUITECTURA, INGENIERÍA AMBIENTAL, INGENIERÍA CIVIL, INGENIERÍA INDUSTRIAL, INGENIERÍA MECÁNICA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS',
        website: 'https://www.upm.es/',
      },
      {
        abbr: 'UAXE',
        name: 'UNIVERSIDAD ALFONSO X EL SABIO',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PASANTIAS DE INVESTIGACION, PRACTICAS / PASANTIAS',
        carrerasUC: 'DERECHO, PSICOLOGÍA, INGENIERÍA CIVIL, INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y MARKETING, MEDICINA HUMANA, ODONTOLOGÍA, PSICOLOGÍA, ADMINISTRACIÓN',
        website: 'https://www.uax.com/',
      },
      {
        abbr: 'UCSP',
        name: 'UNIVERSIDAD CEU SAN PABLO',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PASANTIAS DE INVESTIGACION, PRACTICAS / PASANTIAS',
        carrerasUC: 'DERECHO, CIENCIAS DE LA COMUNICACION, PSICOLOGÍA, ARQUITECTURA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, CONTABILIDAD, ECONOMÍA, MEDICINA HUMANA, ODONTOLOGÍA, ENFERMERÍA, ADMINISTRACIÓN Y GESTIÓN PÚBLICA, INGENIERÍA INDUSTRIAL, PSICOLOGÍA, CONTABILIDAD, ADMINISTRACIÓN',
        website: 'https://www.uspceu.com/',
      },
      {
        abbr: 'UE',
        name: 'UNIVERSIDAD EXTREMADURA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'DERECHO, PSICOLOGÍA, ARQUITECTURA, INGENIERÍA CIVIL, INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, MEDICINA HUMANA, ENFERMERÍA',
        website: 'https://www.unex.es/',
      },
      {
        abbr: 'T',
        name: 'TECNOCAMPUS',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PRACTICAS / PASANTIAS',
        carrerasUC: 'CIENCIAS DE LA COMUNICACION, INGENIERÍA INDUSTRIAL, INGENIERÍA MECÁNICA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ENFERMERÍA, TECNOLOGÍA MÉDICA: TERAPIA FÍSICA Y REHABILITACIÓN, INGENIERÍA INDUSTRIAL, ADMINISTRACIÓN',
        website: 'https://www.tecnocampus.cat/',
      },
      {
        abbr: 'IEDP',
        name: 'INSTITUTO EUROPEO DE PSICOLOGÍA POSITIVA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL VIRTUAL',
        carrerasUC: 'PSICOLOGÍA',
        website: 'https://www.iepp.es/',
      },
      {
        abbr: 'GC',
        name: 'GRUPO CTO',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PRACTICAS / PASANTIAS, ROTACIONES MEDICAS',
        carrerasUC: 'ENFERMERÍA',
        website: 'https://grupocto.es/',
      },
      {
        abbr: 'UDS',
        name: 'UNIVERSIDAD DE SEVILLA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'DERECHO, ADMINISTRACIÓN Y FINANZAS, ECONOMÍA',
        website: 'https://www.us.es/',
      },
    ],
  },
  {
    flagCode: 'us',
    name: 'Estados Unidos De Norteamérica',
    programs: 'Intercambio estudiantil',
    institutions: 2,
    cities: '',
    photo: '/images/gatestowermit.jpg',
    universities: [
      {
        abbr: 'CUFC',
        name: 'Continental University Florida - CUF',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'PSICOLOGÍA, ARQUITECTURA, INGENIERÍA AMBIENTAL, INGENIERÍA CIVIL, INGENIERÍA ELÉCTRICA, INGENIERÍA ELECTRÓNICA, INGENIERÍA EMPRESARIAL, INGENIERÍA INDUSTRIAL, INGENIERÍA MECÁNICA, INGENIERÍA MECATRÓNICA, INGENIERÍA DE MINAS, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y MARKETING, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, ADMINISTRACIÓN Y RECURSOS HUMANOS, CONTABILIDAD, ECONOMÍA, ADMINISTRACIÓN Y GESTIÓN PÚBLICA, INGENIERÍA INDUSTRIAL, PSICOLOGÍA, CONTABILIDAD, ADMINISTRACIÓN',
        website: '',
      },
      {
        abbr: 'CSCT',
        name: 'CHILDREN´S CRISIS TREATMENT CENTER',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PASANTIAS DE INVESTIGACION, PRACTICAS / PASANTIAS',
        carrerasUC: 'PSICOLOGÍA',
        website: 'https://www.cctckids.org/',
      },
    ],
  },
  {
    flagCode: 'ni',
    name: 'Nicaragua',
    programs: 'Intercambio estudiantil',
    institutions: 2,
    cities: '',
    photo: 'https://images.unsplash.com/photo-1597945161640-9366e6587f58?w=900&q=80',
    universities: [
      {
        abbr: 'UNDI',
        name: 'UNIVERSIDAD NACIONAL DE INGENIERÍA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'ARQUITECTURA, INGENIERÍA CIVIL, INGENIERÍA ELÉCTRICA, INGENIERÍA INDUSTRIAL, INGENIERÍA MECÁNICA, INGENIERÍA DE SISTEMAS',
        website: 'https://www.uni.edu.ni/#/',
      },
      {
        abbr: 'UAU',
        name: 'UNIVERSIDAD AMERICANA UAM',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, INTERCAMBIO SEMESTRAL VIRTUAL, DOBLE TITULACION, PASANTIAS DE INVESTIGACION, PRACTICAS / PASANTIAS',
        carrerasUC: 'DERECHO',
        website: 'https://www.uam.edu.ni/',
      },
    ],
  },
  {
    flagCode: 'pt',
    name: 'Portugal',
    programs: 'Intercambio estudiantil',
    institutions: 1,
    cities: '',
    photo: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=900&q=80',
    universities: [
      {
        abbr: 'IPDB',
        name: 'INSTITUTO POLITÉCNICO DE BRAGANÇA',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL',
        carrerasUC: 'ARQUITECTURA, INGENIERÍA AMBIENTAL, INGENIERÍA CIVIL, INGENIERÍA MECÁNICA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y RECURSOS HUMANOS, ENFERMERÍA, TECNOLOGÍA MÉDICA:LABORATORIO CLÍNICO Y ANATOMÍA, TECNOLOGÍA MÉDICA: TERAPIA FÍSICA Y REHABILITACIÓN',
        website: 'https://ipb.pt/pt',
      },
    ],
  },
  {
    flagCode: 'ca',
    name: 'Canadá',
    programs: 'Intercambio estudiantil',
    institutions: 1,
    cities: '',
    photo: '/images/Canada.jpg',
    universities: [
      {
        abbr: 'CAL',
        name: 'CÉGEP ANDRÉ-LAURENDEAU',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PASANTIAS DE INVESTIGACION, PRACTICAS / PASANTIAS',
        carrerasUC: 'ARQUITECTURA, INGENIERÍA CIVIL, INGENIERÍA ELÉCTRICA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y MARKETING, ADMINISTRACIÓN Y RECURSOS HUMANOS, CONTABILIDAD, ECONOMÍA, ENFERMERÍA, ADMINISTRACIÓN',
        website: 'https://claurendeau.qc.ca/',
      },
    ],
  },
  {
    flagCode: 'be',
    name: 'Belgica',
    programs: 'Intercambio estudiantil',
    institutions: 1,
    cities: '',
    photo: 'https://images.unsplash.com/photo-1491557345352-5929e343eb89?w=900&q=80',
    universities: [
      {
        abbr: 'UCLL',
        name: 'UNIVERSITY COLLEGES LEUVEN - LIMBURG',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: '',
        carrerasUC: 'INGENIERÍA ELECTRÓNICA, INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y MARKETING, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, ADMINISTRACIÓN Y RECURSOS HUMANOS, ODONTOLOGÍA, ENFERMERÍA, ADMINISTRACIÓN',
        website: 'https://www.ucll.be/en',
      },
    ],
  },
  {
    flagCode: 'ec',
    name: 'Ecuador',
    programs: 'Intercambio estudiantil',
    institutions: 2,
    cities: '',
    photo: '/images/Ecuador.jpg',
    universities: [
      {
        abbr: 'ESPD',
        name: 'ESCUELA SUPERIOR POLITÉCNICA DEL LITORAL (ESPOL)',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PASANTIAS DE INVESTIGACION, PRACTICAS / PASANTIAS',
        carrerasUC: 'INGENIERÍA CIVIL, INGENIERÍA INDUSTRIAL, INGENIERÍA MECÁNICA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ECONOMÍA, INGENIERÍA INDUSTRIAL, ADMINISTRACIÓN',
        website: 'https://www.espol.edu.ec/es',
      },
      {
        abbr: 'UNDC',
        name: 'UNIVERSIDAD NACIONAL DE CHIMBORAZO',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PASANTIAS DE INVESTIGACION',
        carrerasUC: 'DERECHO, PSICOLOGÍA, ARQUITECTURA, INGENIERÍA CIVIL, INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, MEDICINA HUMANA, ODONTOLOGÍA',
        website: 'https://www.unach.edu.ec/',
      },
    ],
  },
  {
    flagCode: 'de',
    name: 'Alemania',
    programs: 'Intercambio estudiantil',
    institutions: 1,
    cities: '',
    photo: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=900&q=80',
    universities: [
      {
        abbr: 'UOTB',
        name: 'UNIVERSITY OF TECHNOLOGY , BUSINESS AN DESING KONSTANZ',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'INTERCAMBIO SEMESTRAL PRESENCIAL, PASANTIAS DE INVESTIGACION, PRACTICAS / PASANTIAS',
        carrerasUC: 'DERECHO, ARQUITECTURA, INGENIERÍA AMBIENTAL, INGENIERÍA CIVIL, INGENIERÍA ELÉCTRICA, INGENIERÍA EMPRESARIAL, INGENIERÍA INDUSTRIAL, INGENIERÍA MECÁNICA, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, ADMINISTRACIÓN Y MARKETING, ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES, ADMINISTRACIÓN Y RECURSOS HUMANOS, CONTABILIDAD, ECONOMÍA, TECNOLOGÍA MÉDICA:LABORATORIO CLÍNICO Y ANATOMÍA, INGENIERÍA INDUSTRIAL, PSICOLOGÍA, CONTABILIDAD, ADMINISTRACIÓN',
        website: 'https://www.htwg-konstanz.de/',
      },
    ],
  },
  {
    flagCode: 'it',
    name: 'Italia',
    programs: 'Intercambio estudiantil',
    institutions: 1,
    cities: '',
    photo: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=900&q=80',
    universities: [
      {
        abbr: 'TNRC',
        name: 'THE NATIONAL RESEARCH COUNCIL OF ITALY',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'PASANTIAS DE INVESTIGACION',
        carrerasUC: 'INGENIERÍA AMBIENTAL, INGENIERÍA ELÉCTRICA, INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, MEDICINA HUMANA, TECNOLOGÍA MÉDICA:LABORATORIO CLÍNICO Y ANATOMÍA, TECNOLOGÍA MÉDICA: TERAPIA FÍSICA Y REHABILITACIÓN',
        website: 'https://www.cnr.it/',
      },
    ],
  },
  {
    flagCode: 'za',
    name: 'Sudafrica',
    programs: 'Intercambio estudiantil',
    institutions: 1,
    cities: '',
    photo: 'https://images.unsplash.com/photo-1577948000111-9c970dfe3743?w=900&q=80',
    universities: [
      {
        abbr: 'UOJ',
        name: 'UNIVERSITY OF JOHANNESBURG',
        city: '',
        modality: 'Presencial',
        requirements: '',
        deadline: '',
        vacancies: 0,
        convenioType: 'PASANTIAS DE INVESTIGACION',
        carrerasUC: 'DERECHO, PSICOLOGÍA, ARQUITECTURA, INGENIERÍA CIVIL, INGENIERÍA INDUSTRIAL, INGENIERÍA DE SISTEMAS, ADMINISTRACIÓN Y FINANZAS, CONTABILIDAD',
        website: 'https://www.uj.ac.za/',
      },
    ],
  },
];
// Map flagCode → COUNTRIES index for fast lookup
export const COUNTRY_MAP = Object.fromEntries(
  COUNTRIES.map((c, i) => [c.flagCode, i])
);
// ISO_A2 codes that match our countries (GeoJSON property)
export const OUR_ISO = new Set([
  'US','MX','CO','AR','UY','CL','ES','DE','BR','ZA','CN',
  'GT','PY','NI','PT','BE','EC','IT','CR','CA'
]);
