// University data — fixed screen positions matching the original reference image
// side:'left'  → card anchored to left edge, line exits from right side of card
// side:'right' → card anchored to right edge (rightOffset px from right), line exits from left
// side:'top'   → card anchored to top, line exits from bottom center

export const universities = [

  // ── LEFT COLUMN ───────────────────────────────────────────────────────────
  {
    id:'fiu',
    name:'FIU Florida\nInternational University',
    country:'EE.UU.',
    lat: 38.8,  lon: -99.5,
    flagCode:'us',
    logo:'fiu.edu',
    labelPos:{ side:'left', y:'7vh' },
    labelDelay:0.00,
  },
  {
    id:'ibero',
    name:'Universidad\nIberoamericana IBERO',
    country:'México',
    lat: 20.7,  lon:-103.4,
    flagCode:'mx',
    logo:'ibero.mx',
    labelPos:{ side:'left', y:'16vh' },
    labelDelay:0.08,
  },
  {
    id:'monterrey',
    name:'Tecnológico\nde Monterrey',
    country:'México',
    lat: 25.6,  lon:-100.3,
    flagCode:'mx',
    logo:'tec.mx',
    labelPos:{ side:'left', y:'25vh' },
    labelDelay:0.16,
  },
  {
    id:'unam',
    name:'UNAM\nUniversidad Nacional Autónoma',
    country:'México',
    lat: 19.3,  lon: -99.2,
    flagCode:'mx',
    logo:'unam.mx',
    labelPos:{ side:'left', y:'34vh' },
    labelDelay:0.24,
  },
  {
    id:'udea',
    name:'Universidad\nde los Andes',
    country:'Colombia',
    lat:  4.6,  lon: -74.1,
    flagCode:'co',
    logo:'uniandes.edu.co',
    labelPos:{ side:'left', y:'43vh' },
    labelDelay:0.32,
  },
  {
    id:'antioquia',
    name:'Universidad\nde Antioquia',
    country:'Colombia',
    lat:  6.3,  lon: -75.6,
    flagCode:'co',
    logo:'udea.edu.co',
    labelPos:{ side:'left', y:'52vh' },
    labelDelay:0.40,
  },
  {
    id:'ulima',
    name:'Universidad\nde Lima',
    country:'Perú',
    lat:-12.0,  lon: -77.0,
    flagCode:'pe',
    logo:'ulima.edu.pe',
    labelPos:{ side:'left', y:'61vh' },
    labelDelay:0.48,
  },
  {
    id:'uba',
    name:'Universidad\nde Buenos Aires',
    country:'Argentina',
    lat:-34.6,  lon: -58.4,
    flagCode:'ar',
    logo:'uba.ar',
    labelPos:{ side:'left', y:'70vh' },
    labelDelay:0.56,
  },
  {
    id:'ubc',
    name:'UNIVERSIDAD ARGENTINA JOHN F. KENNED',
    country:'Argentina',
    lat:-34.6,  lon: -37.4,
    flagCode:'ar',
    logo:'ubc.ar',
    labelPos:{ side:'left', y:'70vh' },
    labelDelay:0.56,
  },
  {
    id:'udelar',
    name:'Universidad\nde la República',
    country:'Uruguay',
    lat:-34.9,  lon: -56.2,
    flagCode:'uy',
    logo:'udelar.edu.uy',
    labelPos:{ side:'left', y:'79vh' },
    labelDelay:0.64,
  },
  {
    id:'uchile',
    name:'Universidad\nde Chile',
    country:'Chile',
    lat:-33.5,  lon: -70.7,
    flagCode:'cl',
    logo:'uchile.cl',
    labelPos:{ side:'left', y:'88vh' },
    labelDelay:0.72,
  },

  // ── TOP ROW ──────────────────────────────────────────────────────────────
  {
    id:'harvard',
    name:'Harvard\nUniversity',
    country:'EE.UU.',
    lat: 40.2,  lon: -97.5,
    flagCode:'us',
    logo:'harvard.edu',
    labelPos:{ side:'top', x:'33vw', y:72 },
    labelDelay:0.18,
  },
  {
    id:'salamanca',
    name:'Universidad\nde Salamanca',
    country:'España',
    lat: 41.0,  lon:  -5.7,
    flagCode:'es',
    logo:'usal.es',
    labelPos:{ side:'top', x:'44vw', y:72 },
    labelDelay:0.26,
  },
  {
    id:'pku',
    name:'Peking\nUniversity',
    country:'China',
    lat: 39.9,  lon: 116.4,
    flagCode:'cn',
    logo:'pku.edu.cn',
    labelPos:{ side:'top', x:'66vw', y:72 },
    labelDelay:0.42,
  },

  // ── RIGHT COLUMN ──────────────────────────────────────────────────────────
  {
    id:'ceu',
    name:'CEU\nSan Pablo',
    country:'España',
    lat: 40.4,  lon:  -3.7,
    flagCode:'es',
    logo:'ceu.es',
    labelPos:{ side:'right', rightOffset:228, y:'9vh' },
    labelDelay:0.06,
  },
  {
    id:'fundacion',
    name:'Fundación\nUniversidad-Empresa',
    country:'España',
    lat: 38.5,  lon:  -5.5,
    flagCode:'es',
    logo:'fue.es',
    labelPos:{ side:'right', rightOffset:228, y:'21vh' },
    labelDelay:0.14,
  },
  {
    id:'karlsruhe',
    name:'Universitas\nKarlsruhe (KIT)',
    country:'Alemania',
    lat: 49.0,  lon:   8.4,
    flagCode:'de',
    logo:'kit.edu',
    labelPos:{ side:'right', rightOffset:228, y:'33vh' },
    labelDelay:0.22,
  },
  {
    id:'usp',
    name:'Universidade\nde São Paulo',
    country:'Brasil',
    lat:-23.6,  lon: -46.7,
    flagCode:'br',
    logo:'usp.br',
    labelPos:{ side:'right', rightOffset:228, y:'45vh' },
    labelDelay:0.30,
  },
  {
    id:'uc',
    name:'Universidad\nContinental',
    country:'Perú',
    lat:-12.0,  lon: -76.0,
    flagCode:'pe',
    logo:'ucontinental.edu.pe',
    labelPos:{ side:'right', rightOffset:228, y:'57vh' },
    labelDelay:0.38,
  },
  {
    id:'unmsm',
    name:'Univ. Nacional\nMayor de San Marcos',
    country:'Perú',
    lat:-13.0,  lon: -75.5,
    flagCode:'pe',
    logo:'unmsm.edu.pe',
    labelPos:{ side:'right', rightOffset:228, y:'69vh' },
    labelDelay:0.46,
  },
  {
    id:'uct',
    name:'University\nof Cape Town',
    country:'Sudáfrica',
    lat:-33.9,  lon:  18.4,
    flagCode:'za',
    logo:'uct.ac.za',
    labelPos:{ side:'right', rightOffset:228, y:'79vh' },
    labelDelay:0.54,
  },
];
